apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yatri-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: http://gitea.gitea.svc.cluster.local:3000/yatri/platform.git
    targetRevision: main
    path: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
