apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yatri-app.fullname" . }}-config
  labels:
    {{- include "yatri-app.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  index.html: |
    <html>
      <body>
        <h1>{{ .Values.config.GREETING }}</h1>
        <p>release: {{ .Release.Name }}</p>
        <p>chart:   {{ .Chart.Name }}-{{ .Chart.Version }}</p>
        <p>app:     {{ .Values.image.tag | default .Chart.AppVersion }}</p>
        <p>env:     {{ .Values.config.APP_ENV }}</p>
      </body>
    </html>
