apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: yatri
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
